# Site settings
title: Oldtimerclub Reith im Alpbachtal
description: Wir sind eine illustre Gruppe mit Spaß an historischen Fahrzeugen. Dies beinhaltet unter anderem die Restauration, Pflege und natürlich das Fahren mit unseren Oldies.
baseurl: ''
url: http://oc-reith.github.io

# Build settings
markdown: kramdown
sass:
  style: :compressed

# Exclusions
exclude: [
  '.gitignore',
  'CNAME',
  'bower.json',
  'bower_components',
  'Gemfile',
  'Gemfile.lock',
  'node_modules',
  'package.json',
  '_cars/0000/'
]

# Collections
collections:
  cars:
    output: true
    permalink: /fahrzeuge/:path.html