# Site settings
title: Oldtimerclub Reith im Alpbachtal
description: >
  Wir sind eine illustre Gruppe mit Spaß an historischen Fahrzeugen.
  Dies beinhaltet unter anderem die Restauration, Pflege und
  natürlich das Fahren mit unseren Oldies.
baseurl: ''
url: https://oldtimer-reith.tirol

# Build settings
markdown: kramdown
sass:
  style: :compressed

# Plugins
gems:
  - jekyll-coffeescript
  - jekyll-redirect-from
  - jekyll-sitemap

# Exclusions
exclude: [
  '.gitignore',
  'ReadMe.md',
  'CNAME',
  'bower.json',
  'bower_components',
  'Gemfile',
  'Gemfile.lock',
  'node_modules',
  'package.json',
  '_fahrzeuge/0000'
]

# Collections
collections:
  fahrzeuge:
    output: true
    permalink: /fahrzeuge/:path.html
