# Site settings
title: Oldtimerclub Reith im Alpbachtal
description: Wir sind eine illustre Gruppe mit Spaß an historischen Fahrzeugen. Dies beinhaltet unter anderem die Restauration, Pflege und natürlich das Fahren mit unseren Oldies.
baseurl: ''
url: http://oldtimer-reith.tirol

# Build settings
markdown: kramdown
sass:
  style: :compressed

# Sitemap Plugin
gems:
  - jekyll-sitemap
  - jekyll-redirect-from

# Exclusions
exclude: [
  '.gitignore',
  'CNAME',
  'bower.json',
  'bower_components',
  'Gemfile',
  'Gemfile.lock',
  'node_modules',
  'package.json',
  '_vehicles/fahrzeuge/0000/'
]

# Collections
collections:
  vehicles:
    output: true
    permalink: /:path.html